# Generated by Django 3.2.19 on 2023-08-12 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0004_alter_message_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='chat_messages.room'),
        ),
    ]
